Window("Calculator").WinButton("Button").Click @@ hightlight id_;_67290_;_script infofile_;_ZIP::ssf1.xml_;_
Window("Calculator").WinButton("Button_2").Click @@ hightlight id_;_67314_;_script infofile_;_ZIP::ssf2.xml_;_
Window("Calculator").WinButton("Button_3").Click @@ hightlight id_;_67302_;_script infofile_;_ZIP::ssf3.xml_;_
Window("Calculator").WinButton("Button_2").Click @@ hightlight id_;_67314_;_script infofile_;_ZIP::ssf4.xml_;_
Window("Calculator").WinButton("Button_4").Click @@ hightlight id_;_67292_;_script infofile_;_ZIP::ssf5.xml_;_
Window("Calculator").WinButton("Button_5").Click @@ hightlight id_;_67312_;_script infofile_;_ZIP::ssf6.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_67300_;_script infofile_;_ZIP::ssf7.xml_;_
Window("Calculator").WinButton("Button_7").Click @@ hightlight id_;_67328_;_script infofile_;_ZIP::ssf8.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_67298_;_script infofile_;_ZIP::ssf9.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_67298_;_script infofile_;_ZIP::ssf10.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_67298_;_script infofile_;_ZIP::ssf11.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_67298_;_script infofile_;_ZIP::ssf12.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_67298_;_script infofile_;_ZIP::ssf13.xml_;_
Window("Calculator").WinButton("Button").Click @@ hightlight id_;_67290_;_script infofile_;_ZIP::ssf14.xml_;_
Window("Calculator").WinButton("Button_2").Click @@ hightlight id_;_67314_;_script infofile_;_ZIP::ssf15.xml_;_
Window("Calculator").WinButton("Button").Click @@ hightlight id_;_67290_;_script infofile_;_ZIP::ssf16.xml_;_
Window("Calculator").WinButton("Button_9").Click @@ hightlight id_;_132810_;_script infofile_;_ZIP::ssf17.xml_;_
Window("Calculator").WinButton("Button_9").Click @@ hightlight id_;_132810_;_script infofile_;_ZIP::ssf18.xml_;_
Window("Calculator").WinButton("Button_9").Click @@ hightlight id_;_132810_;_script infofile_;_ZIP::ssf19.xml_;_
Window("Calculator").Close
